apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: build
    namespace: default
  - kind: ServiceAccount
    name: build
    namespace: kube-system
---

apiVersion: v1
kind: LimitRange
metadata:
  name: build
  namespace: default
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 0.2
    defaultRequest:
      memory: 250Mi
      cpu: 0.1
    max:
      memory: 500Mi
      cpu: 0.5
    min:
      memory: 10Mi
      cpu: 0.05
    type: Container

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: build
  namespace: default
spec:
  hard:
    requests.cpu: 2
    requests.memory: 3Gi
    limits.cpu: 3
    limits.memory: 5Gi
    pods: 15
